# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 11:53
from __future__ import unicode_literals
from django.core.management import call_command
from django.db import migrations


def load_initial_data(apps, schema_editor):
    call_command('loaddata', "initial_data", app_label='Database',)


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('Database', 'hote_internal_server'),
        ('sites', '0002_alter_domain_unique'),
        ("auth", '0007_alter_validators_add_error_messages')
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
