# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20170124_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='backbone',
            field=models.BooleanField(db_column='backbone', default=False),
            preserve_default=False,
        ),
    ]
