# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_port_backbone'),
    ]

    operations = [
        migrations.RenameField('port','usable','enabled'),
    ]