# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20160205_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='hote',
            name='internal_server',
            field=models.BooleanField(default=False),
        ),
    ]
